name: Generate Snake

on:
  schedule:
    - cron: "10 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate snake animation (SVG)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          output_dir: output
          file_name: github-contribution-grid-snake.svg
          palette: github-dark
          snake_color: '#39ff14'
          dot_color: '#ffffff'
          image_type: svg
          compact: 'true'

      - name: Commit & push output to `output` branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: output
          commit_message: "chore: update contribution snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
